server:
  port: 8080
spring:
  application:
    name: "ms-autenticacion"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuariosByMail: "/api/v1/usuarios/{mail}"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya
    schema: auth
    username: admin
    password: admin123
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

# OpenAPI Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  packages-to-scan: co.com.crediya.autenticacion.api
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false