server:
  port: 8080
spring:
  application:
    name: "ms-autenticacion"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuariosByMail: "/api/v1/usuarios/{mail}"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya
    schema: public
    username: admin
    password: admin123